[programs.localnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "Fs5wSa7GYtTqivXGqHyx673v5oPuD5Cb7ij9utsFKdLb"

[programs.devnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "Fs5wSa7GYtTqivXGqHyx673v5oPuD5Cb7ij9utsFKdLb"

[programs.mainnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "DHepkufWDLJ9DCD37nbEDbPSFKjGiziQ6Lbgo1zgGX7S"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
seeds = true
