[programs.localnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "HomrJ8vvXe5FpqN6zfUSYK9JLnMyDmbJvZJYDnhoZhWE"

[programs.devnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "HomrJ8vvXe5FpqN6zfUSYK9JLnMyDmbJvZJYDnhoZhWE"

[programs.mainnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "DHepkufWDLJ9DCD37nbEDbPSFKjGiziQ6Lbgo1zgGX7S"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
seeds = true

[test]
startup_wait = 10000

[test.validator]
url = "https://api.devnet.solana.com"

# Collection mint key
[[test.validator.clone]]
address = "GcMPukzjZWfY4y4KVM3HNdqtZTf5WyTWPvL4YXznoS9c"

# Collection metadata
[[test.validator.clone]]
address = "127CfcfCk5H8zSNDvSLJjKLVxwb6YP6hPK4TGRmVMNtE"

# authorized user key
[[test.validator.clone]]
address = "CKQZCHQTJJDXzfkcodYZ4i6adjjL5cwuiqnFQgrgPh67"

# associated token account for authorized user
[[test.validator.clone]]
address = "9SEWPdMDNWuvDhsjvzUGzLeAjLpFgthrnBjcCwmvsPA6"

# Owner key
[[test.validator.clone]]
address = "E5rGQH5XXds6ZJLWnx9mjtoc2JKDF8rchK5UeDCgkbuV"

# unauthorized user key
[[test.validator.clone]]
address = "A5E92mr5PSCHyeSRB1JwPE4tYCjMCGkY3aEHr3TYZ7xg"

# zero-balance user key
[[test.validator.clone]]
address = "GFUfnHVCpDLgoVfuvUEYnqwogn5AfPkrW57EzK2TKVFC"

# associated token account for zero-balance user
[[test.validator.clone]]
address = "ERrPQisQyjdNTMXej1hfSrV7c3eWMARykgS5KRR5MmCu"

# SOLID color #6
[[test.validator.clone]]
address = "3m1CQGFk31VtcBU6gEQqcqvSeH265bGX52URHAy7aMwZ"

# SOLID color #6 metadata
[[test.validator.clone]]
address = "H2wPow8g9KCgXPeUcM4djJECK3ji4NJeiQQ2HgWHA3Sf"

# SOLID color #1
[[test.validator.clone]]
address = "AGGEiRQSRdqSRvWuxotuNinDoayQH8cVRhNcSsFJQDVp"

# SOLID color #1 metadata
[[test.validator.clone]]
address = "3sQSbdWqK8hPMzoA89S8pRuFSkdeU7tZHvThAyKgW4Vg"
