[programs.localnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "Fs5wSa7GYtTqivXGqHyx673v5oPuD5Cb7ij9utsFKdLb"
offloadbox = "BnQpgE5tiD4t7a6TqZiH3yoSRW2eaDZ9av65hXCR7qoQ"

[programs.devnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "Fs5wSa7GYtTqivXGqHyx673v5oPuD5Cb7ij9utsFKdLb"
offloadbox = "BnQpgE5tiD4t7a6TqZiH3yoSRW2eaDZ9av65hXCR7qoQ"

[programs.mainnet]
messaging = "BHJ4tRcogS88tUhYotPfYWDjR4q7MGdizdiguY3N54rb"
postbox = "Fs5wSa7GYtTqivXGqHyx673v5oPuD5Cb7ij9utsFKdLb"
offloadbox = "BnQpgE5tiD4t7a6TqZiH3yoSRW2eaDZ9av65hXCR7qoQ"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[features]
seeds = true
