name: Build Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Without this anchor install fails with "'Unable to find libudev"
    - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
    - name: Build
      run: cargo build --verbose
    - name: Install Anchor
      run: cargo install --git https://github.com/project-serum/anchor --tag v0.20.1 anchor-cli --locked
    - name: Run Anchor test
      run: anchor test
