name: Build Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    # Without this anchor install fails with "'Unable to find libudev"
    - run: sudo apt-get update && sudo apt-get install -y pkg-config build-essential libudev-dev
    - uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}-2
    - name: Remove existing rust binaries
      run: rm -rf ~/.cargo/ || true
    - name: Install Rust via Rustup (Rquired for Solana's Anchor)
      run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
        #      uses: actions-rs/toolchain@v1
        #      with:
        #        toolchain: stable
        #        override: true
        #        components: rustfmt, clippy
    - name: Control rust via rustup
      run: rustup update && source $HOME/.cargo/env
    - name: Test bpf is present # This is faster than building anchor first
      run: cargo build-bpf
    - name: Build
      run: cargo build --verbose
    - name: Install Anchor (if not already in the cache)
      run: anchor || cargo install --git https://github.com/project-serum/anchor --tag v0.20.1 anchor-cli --locked
    - name: Run Anchor test
      run: anchor test
