name: Test full codebase (Solana Program and Typescript library)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: install solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.9.9/install)"

      - name: add solana to path
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: print solana version
        run: solana --version
      - name: gen wallet
        run: solana-keygen new
      - name: view config detail
        run: solana config get

      - name: Install Anchor
        run: npm install -g @project-serum/anchor-cli@0.24.2
      - name: Test cargo bpf
        run: cargo build-bpf
      - name: install yarn
        run: npm install -g yarn
      - run: yarn install
      - name: Run Anchor test
        run: anchor test
      - name: Test Dispatch client
        run: cd usedispatch_client && npm install && cd ..
      - name: Build Dispatch CLI (no tests yet)
        run: cd usedispatch_cli && npm install && cd ..
