name: Build Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: install rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - uses: Swatinem/rust-cache@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
      - name: install solana
        run: sh -c "$(curl -sSfL https://release.solana.com/v1.8.0/install)"

      - name: add solana to path
        run: echo "$HOME/.local/share/solana/install/active_release/bin" >> $GITHUB_PATH

      - name: print solana version
        run: solana --version

      - name: Install Anchor
        run: npm install -g @project-serum/anchor-cli
      - name: Test cargo bpf
        run: cargo build-bpf
      - name: install yarn
        run: npm install -g yarn
      - run: yarn install
      - name: Run Anchor test
        run: anchor test
